### ISSUE TITLE
Choose followed by colon separated numbers results in a Bible lookup

### ISSUE THREAD

**Issue by Teron** [aquarion/lampstand#7]
Lampstand interprets "Choose" followed by a pair of numbers seperated by a colon followed by any string as a trigger to perform a bible lookup instead of a Choose response.  It should probably not do this.

Relevant logs:
>< Teron> Lampstand: Choose a or b?
>13/02|19:30:26 <Lampstand> Teron: a
>13/02|19:30:29 < Teron> Lampstand: Choose a:c or b?
>13/02|19:30:29 <Lampstand> Teron: b
>13/02|19:30:31 < Teron> Lampstand: Choose a:c or b?
>13/02|19:30:31 <Lampstand> Teron: b
>13/02|19:30:32 < Teron> Lampstand: Choose a:c or b?
>13/02|19:30:33 <Lampstand> Teron: a:c
>13/02|19:30:40 < Teron> Lampstand: Choose 1 or 2?
>13/02|19:30:41 <Lampstand> Teron: 2
>13/02|19:30:43 < Teron> Lampstand: Choose 1 or 2:2?
>13/02|19:30:44 <Lampstand> Teron: 1
>13/02|19:30:45 < Teron> Lampstand: Choose 1 or 2:2?
>13/02|19:30:45 <Lampstand> Teron: 1
>13/02|19:30:50 < Teron> Lampstand: Choose 1:2 or 2:2?
>13/02|19:30:51 <Lampstand> ERROR: No passage found for your query. [ESV]
>13/02|19:30:55 < Teron> Lampstand: 1:2
>13/02|19:31:14 < Teron> Lampstand: Choose 1:2
>13/02|19:31:15 <Lampstand> ERROR: No passage found for your query. [ESV]

(The string "Lampstand" in "\<Lampstand\>" should have an @ in front of it, but that would trigger notifications to the user Lampstand)

**Comment by Teron** [comment]
I've forked and will patch in the next day or two; from my initial poking it will not be a big change.

**Comment by Teron** [comment]
Ok, so I have three different solutions:

#### [issue7-lookaheadfix](teron/lampstand@11d0f55)
##### Pros:
* It works
* It is a two line (bar comments) change

##### Cons:
* It means that the bible module needs to know (sort of) about the choose module

#### [issue7-configfix](teron/lampstand@bbb6a3c)
##### Pros:
* It works
* It is a two line (bar comments) change
* The bible module does not need to know about the choose module

##### Cons: 
* Fragile, if someone overrides the relevant bit of the default config or changes the config later, the bug could very easily reappear and be quite hard to debug.

#### [issue7-explicitbookmatchfix](teron/lampstand@d90d1b6)
##### Pros:
* Keeps the bible module self-contained
* Will mean that bugs like this don't happen in the future if other modules are loaded after bible and are called by <string> <number>:<number>
* Relatively easy to extend to numbered books (something that has come up in testing and I should put an issue in for)

##### Cons:
* Not finished yet
* Will take quite a bit more work than the other fixes


Anyone got opinions on this?  I'm tempted to just submit a pull request for [issue7-lookaheadfix](teron/lampstand@11d0f55) , but [issue7-explicitbookmatchfix](teron/lampstand@d90d1b6) is theoretically better in my mind.

**Comment by aquarion** [comment]
Of these, I think I prefer the Look Ahead or Config fixes. The explicit book match is a more classically neat solution, but remember that channel regexes run on every line submitted, and the bible functionality simply isn't a core enough module to have that amount of per-line CPU thrown at it.

**Comment by Teron** [comment]
The per-line running and cpu constraints are good points that I had not considered.  I will go for the Lookahead fix.
